In [12]:
import sys
import os

In [13]:
sys.path.append(os.path.abspath('../..'))

In [14]:
from src.preprocessing import load_and_clean_candidats, load_and_clean_nuances

In [15]:
df = load_and_clean_candidats()
df.head()

,Code du département,Libellé du département,Code commune,Libellé commune,N° Panneau Liste,Libellé abrégé liste,Libellé Etendu Liste,Nuance Liste,N° candidat,Sexe candidat,Nom candidat,Prénom candidat,Nationalité,Candidat au conseil communautaire
0,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,1,M,FABRE,Daniel,Française,O
1,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,2,F,SONNERY,Sylvie,Française,O
2,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,3,M,DE BOISSIEU,Christian,Française,O
3,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,4,F,BLANC FALCON,Liliane,Française,O
4,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,5,M,FORTIN,Christophe,Française,N

In [16]:
df.shape

(546142, 14)

In [17]:
df[['Nom candidat', 'Prénom candidat']].nunique()

Nom candidat       179900
Prénom candidat     31566
dtype: int64

In [18]:
df['nom prenom'] = df['Nom candidat'] + ' ' + df['Prénom candidat']

In [19]:
df['nom prenom'].nunique()

509561

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546142 entries, 0 to 546141
Data columns (total 15 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Code du département                546142 non-null  object
 1   Libellé du département             546142 non-null  object
 2   Code commune                       546142 non-null  object
 3   Libellé commune                    546142 non-null  object
 4   N° Panneau Liste                   546142 non-null  int64
 5   Libellé abrégé liste               546101 non-null  object
 6   Libellé Etendu Liste               545915 non-null  object
 7   Nuance Liste                       337473 non-null  object
 8   N° candidat                        546123 non-null  object
 9   Sexe candidat                      546142 non-null  object
 10  Nom candidat                       546142 non-null  object
 11  Prénom candidat                    546142 non-null  object
 12  Nationalité                        546079 non-null  object
 13  Candidat au conseil communautaire  546055 non-null  object
 14  nom prenom                         546142 non-null  object
dtypes: int64(1), object(14)
memory usage: 62.5+ MB

In [21]:
df['Nuance Liste'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
546137    False
546138    False
546139    False
546140    False
546141    False
Name: Nuance Liste, Length: 546142, dtype: bool

In [22]:
df.merge(load_and_clean_nuances(), how='left', left_on='Nuance Liste', right_on='Nuance')

,Code du département,Libellé du département,Code commune,Libellé commune,N° Panneau Liste,Libellé abrégé liste,Libellé Etendu Liste,Nuance Liste,N° candidat,Sexe candidat,Nom candidat,Prénom candidat,Nationalité,Candidat au conseil communautaire,nom prenom,Nuance,Libellé
0,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,1,M,FABRE,Daniel,Française,O,FABRE Daniel,LDVC,Divers centre
1,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,2,F,SONNERY,Sylvie,Française,O,SONNERY Sylvie,LDVC,Divers centre
2,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,3,M,DE BOISSIEU,Christian,Française,O,DE BOISSIEU Christian,LDVC,Divers centre
3,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,4,F,BLANC FALCON,Liliane,Française,O,BLANC FALCON Liliane,LDVC,Divers centre
4,1,Ain,4,Ambérieu-en-Bugey,1,UNIS POUR AMBERIEU,UNIS POUR AMBERIEU,LDVC,5,M,FORTIN,Christophe,Française,N,FORTIN Christophe,LDVC,Divers centre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546137,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,2,ENSEMBLE POUR CONSTRUIRE,ENSEMBLE POUR CONSTRUIRE,LDVG,25,F,BRIAND,Joanne,Française,N,BRIAND Joanne,LDVG,Liste divers gauche
546138,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,2,ENSEMBLE POUR CONSTRUIRE,ENSEMBLE POUR CONSTRUIRE,LDVG,26,M,LEGENTIL,Olivier,Française,N,LEGENTIL Olivier,LDVG,Liste divers gauche
546139,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,2,ENSEMBLE POUR CONSTRUIRE,ENSEMBLE POUR CONSTRUIRE,LDVG,27,F,BRY,Gisèle,Française,N,BRY Gisèle,LDVG,Liste divers gauche
546140,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,2,ENSEMBLE POUR CONSTRUIRE,ENSEMBLE POUR CONSTRUIRE,LDVG,28,M,DURAND,Sébastien,Française,N,DURAND Sébastien,LDVG,Liste divers gauche
546141,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,2,ENSEMBLE POUR CONSTRUIRE,ENSEMBLE POUR CONSTRUIRE,LDVG,29,F,JEZEQUEL,Bianca,Française,N,JEZEQUEL Bianca,LDVG,Liste divers gauche