In [1]:
import os
import sys

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import load_and_clean_2001_res, load_and_clean_2008_res, load_and_clean_2014_res, load_and_clean_2020_res_tour1, load_and_clean_2020_res_tour2

In [4]:
df_2001 = load_and_clean_2001_res()
df_2008 = load_and_clean_2008_res()
df_2014 = load_and_clean_2014_res()
df_2020_tour1 = load_and_clean_2020_res_tour1()
df_2020_tour2 = load_and_clean_2020_res_tour2()

In [5]:
df_2001

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Population,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,...,% BlNuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,Nuance Liste,Libellé Abrégé Liste,Voix,% Voix/Ins,% Voix/Exp,rang_liste
0,1,AIN,4,Ambérieu-en-Bugey,11386,7137,2975,41.68,4162,58.32,...,7.04,3869,54.21,92.96,LGA,Liste de gauche,1081.0,15.15,27.94,1
1,1,AIN,14,Arbent,3610,1656,609,36.78,1047,63.22,...,6.97,974,58.82,93.03,LDG,Liste divers gauche,309.0,18.66,31.72,1
2,1,AIN,33,Bellegarde-sur-Valserine,10843,5745,2473,43.05,3272,56.95,...,5.65,3087,53.73,94.35,LGA,Liste de gauche,1128.0,19.63,36.54,1
3,1,AIN,34,Belley,7999,4502,1299,28.85,3203,71.15,...,4.03,3074,68.28,95.97,LGA,Liste de gauche,1419.0,31.52,46.16,1
4,1,AIN,43,Beynost,3530,2585,923,35.71,1662,64.29,...,5.60,1569,60.70,94.40,LDD,Liste divers droite,1569.0,60.70,100.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21528,93,SEINE SAINT-DENIS,51,Noisy-le-Grand,58217,27830,13353,47.98,14477,52.02,...,3.65,13948,50.12,96.35,LMN,Liste MNR,640.0,2.30,4.59,8
22154,25,DOUBS,56,Besançon,117295,60975,27784,45.57,33191,54.43,...,3.86,31909,52.33,96.14,LMN,Liste MNR,849.0,1.39,2.66,9
22374,33,GIRONDE,63,Bordeaux,215191,110915,50111,45.18,60804,54.82,...,3.10,58918,53.12,96.90,LMN,Liste MNR,479.0,0.43,0.81,9
23685,75,PARIS,056SR10,PARIS Secteur 10,89612,37092,14295,38.54,22797,61.46,...,2.29,22274,60.05,97.71,LMN,Liste MNR,688.0,1.85,3.09,9
23688,75,PARIS,056SR13,PARIS Secteur 13,171533,85615,31196,36.44,54419,63.56,...,3.08,52745,61.61,96.92,LMN,Liste MNR,1238.0,1.45,2.35,9

In [6]:
df_2008

,Date export,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Code du bureau de vote,Inscrits,Abstentions,% Abs/Ins,Votants,...,% Exp/Vot,Code Nuance,Sexe,Nom,Prénom,Liste,Sièges,Voix,% Voix/Ins,% Voix/Exp
0,23/05/2008 13:26:36,ZA,GUADELOUPE,101,Les Abymes,0001,540,178,32.96,362,...,96.13,LSOC,M,NABAJOTH,Alix,L'ï¿½LAN ABYMIEN,0,22,4.07,6.32
1,23/05/2008 13:26:36,ZA,GUADELOUPE,101,Les Abymes,0001,540,178,32.96,362,...,96.13,LDVG,M,JALTON,Eric,ABYMES AVENIR,0,144,26.67,41.38
2,23/05/2008 13:26:36,ZA,GUADELOUPE,101,Les Abymes,0001,540,178,32.96,362,...,96.13,LDVG,M,MARSIN,Daniel,UNIS POUR LES ABYMES,0,182,33.70,52.30
3,23/05/2008 13:26:36,ZA,GUADELOUPE,101,Les Abymes,0002,273,98,35.90,175,...,89.14,LSOC,M,NABAJOTH,Alix,L'ï¿½LAN ABYMIEN,0,12,4.40,7.69
4,23/05/2008 13:26:36,ZA,GUADELOUPE,101,Les Abymes,0002,273,98,35.90,175,...,89.14,LDVG,M,JALTON,Eric,ABYMES AVENIR,0,86,31.50,55.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140523,23/05/2008 13:20:52,95,VAL D'OISE,582,Sannois,0015,888,345,38.85,543,...,97.79,LSOC,M,DULOUARD,Christophe,AGIR POUR LES SANNOISIENS,0,223,25.11,42.00
140524,23/05/2008 13:20:52,95,VAL D'OISE,582,Sannois,0015,888,345,38.85,543,...,97.79,LMAJ,M,PATERNOTTE,Yanick,UNION POUR SANNOIS 2008,0,269,30.29,50.66
140525,23/05/2008 13:20:52,95,VAL D'OISE,582,Sannois,0016,815,350,42.94,465,...,98.06,LCOM,F,JEANTILS,Josiane,UNION A GAUCHE AVEC VOUS,0,25,3.07,5.48
140526,23/05/2008 13:20:52,95,VAL D'OISE,582,Sannois,0016,815,350,42.94,465,...,98.06,LSOC,M,DULOUARD,Christophe,AGIR POUR LES SANNOISIENS,0,146,17.91,32.02
140527,23/05/2008 13:20:52,95,VAL D'OISE,582,Sannois,0016,815,350,42.94,465,...,98.06,LMAJ,M,PATERNOTTE,Yanick,UNION POUR SANNOIS 2008,0,285,34.97,62.50

In [7]:
df_2014

,N° tour,Code département,Code commune,Nom de la commune,N° de bureau de vote,Inscrits,Votants,Exprimés,N° de dépôt de la liste,Nom du candidat tête de liste,Prénom du candidat tête de liste,Code nuance de la liste,Nombre de voix
0,1,01,1,L'Abergement-Clémenciat,0001,599,355,341,4,BOUILLOUX,Delphine,NC,324
1,1,01,1,L'Abergement-Clémenciat,0001,599,355,341,16,EVALET-TAPONAT,Line,NC,316
2,1,01,1,L'Abergement-Clémenciat,0001,599,355,341,3,BERAUD,Zélie,NC,315
3,1,01,1,L'Abergement-Clémenciat,0001,599,355,341,14,VACLE,Robert,NC,300
4,1,01,1,L'Abergement-Clémenciat,0001,599,355,341,10,MARGUIN,Jean Paul,NC,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...
692024,2,ZP,58,Uturoa,0002,1029,804,796,2,GUILLOUX,Germain,LDIV,102
692025,2,ZP,58,Uturoa,0002,1029,804,796,3,TEROOATEA,Sylviane,LDVD,465
692026,2,ZP,58,Uturoa,0003,1120,898,878,4,BROTHERSON,Matahi,LDVD,344
692027,2,ZP,58,Uturoa,0003,1120,898,878,3,TEROOATEA,Sylviane,LDVD,435
692028,2,ZP,58,Uturoa,0003,1120,898,878,2,GUILLOUX,Germain,LDIV,99

In [8]:
df_2020_tour1

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Code du bureau de vote,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,...,% Exp/Vot,N.Pan.,Code Nuance,Sexe,Nom,Prénom,Liste,Voix,% Voix/Ins,% Voix/Exp
0,1,Ain,1,L'Abergement-Clémenciat,1,622,340,54.66,282,45.34,...,97.16,2.0,NC,M,BOULON,Daniel,NaN,230.0,36.98,83.94
1,1,Ain,1,L'Abergement-Clémenciat,1,622,340,54.66,282,45.34,...,97.16,3.0,NC,M,BARRET,Yohann,NaN,264.0,42.44,96.35
2,1,Ain,1,L'Abergement-Clémenciat,1,622,340,54.66,282,45.34,...,97.16,4.0,NC,F,BEAUDET,Sylvie,NaN,258.0,41.48,94.16
3,1,Ain,1,L'Abergement-Clémenciat,1,622,340,54.66,282,45.34,...,97.16,5.0,NC,F,BERAUD,Zélie,NaN,262.0,42.12,95.62
4,1,Ain,1,L'Abergement-Clémenciat,1,622,340,54.66,282,45.34,...,97.16,6.0,NC,F,BOUILLOUX,Delphine,NaN,267.0,42.93,97.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545347,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,1,1405,613,43.63,792,56.37,...,94.82,2.0,LDVG,F,CLAIREAUX,Karine,ENSEMBLE POUR CONSTRUIRE,305.0,21.71,40.61
545348,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,2,1375,612,44.51,763,55.49,...,93.58,1.0,LDVG,M,CAMBRAY,Yannick,CAP SUR l'AVENIR,428.0,31.13,59.94
545349,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,2,1375,612,44.51,763,55.49,...,93.58,2.0,LDVG,F,CLAIREAUX,Karine,ENSEMBLE POUR CONSTRUIRE,286.0,20.80,40.06
545350,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,3,1714,711,41.48,1003,58.52,...,94.12,1.0,LDVG,M,CAMBRAY,Yannick,CAP SUR l'AVENIR,612.0,35.71,64.83
545351,ZS,Saint-Pierre-et-Miquelon,502,Saint-Pierre,3,1714,711,41.48,1003,58.52,...,94.12,2.0,LDVG,F,CLAIREAUX,Karine,ENSEMBLE POUR CONSTRUIRE,332.0,19.37,35.17

In [9]:
df_2020_tour2

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Code du bureau de vote,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,...,% Exp/Vot,N.Pan.,Code Nuance,Sexe,Nom,Prénom,Liste,Voix,% Voix/Ins,% Voix/Exp
0,01,Ain,12,Aranc,0001,273,120,43.96,153,56.04,...,98.04,7.0,NC,M,PIRES,Hervé,NaN,0.0,0.00,0.00
1,01,Ain,12,Aranc,0001,273,120,43.96,153,56.04,...,98.04,11.0,NC,M,GOYET,Eric,NaN,62.0,22.71,41.33
2,01,Ain,12,Aranc,0001,273,120,43.96,153,56.04,...,98.04,13.0,NC,F,PALLET,Monique,NaN,88.0,32.23,58.67
3,01,Ain,12,Aranc,0001,273,120,43.96,153,56.04,...,98.04,14.0,NC,F,TRICHARD,Elodie,NaN,0.0,0.00,0.00
4,01,Ain,12,Aranc,0001,273,120,43.96,153,56.04,...,98.04,15.0,NC,M,DAVID,Guy,NaN,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85617,ZP,Polynésie française,758,Uturoa,0001,1185,275,23.21,910,76.79,...,97.91,2.0,LDVD,F,TEROOATEA,Sylviane,OUTUROA TO TATOU OIRE,472.0,39.83,52.97
85618,ZP,Polynésie française,758,Uturoa,0002,1032,178,17.25,854,82.75,...,98.13,1.0,LDVD,M,BROTHERSON,Matahi,TE REO AMUI NO UTUROA,402.0,38.95,47.97
85619,ZP,Polynésie française,758,Uturoa,0002,1032,178,17.25,854,82.75,...,98.13,2.0,LDVD,F,TEROOATEA,Sylviane,OUTUROA TO TATOU OIRE,436.0,42.25,52.03
85620,ZP,Polynésie française,758,Uturoa,0003,1221,182,14.91,1039,85.09,...,98.46,1.0,LDVD,M,BROTHERSON,Matahi,TE REO AMUI NO UTUROA,560.0,45.86,54.74
85621,ZP,Polynésie française,758,Uturoa,0003,1221,182,14.91,1039,85.09,...,98.46,2.0,LDVD,F,TEROOATEA,Sylviane,OUTUROA TO TATOU OIRE,463.0,37.92,45.26

In [11]:
print("df 2001 ", df_2001.columns)
print("df 2008 ", df_2008.columns)
print("df 2014 ", df_2014.columns)
print("df 2020 tour 1", df_2020_tour1.columns)
print("df 2020 tour 2", df_2020_tour2.columns)

df 2001  Index(['Code du département', 'Libellé du département', 'Code de la commune',
       'Libellé de la commune', 'Population', 'Inscrits', 'Abstentions',
       '% Abs/Ins', 'Votants', '% Vot/Ins', 'Blancs et nuls', '% BlNuls/Ins',
       '% BlNuls/Vot', 'Exprimés', '% Exp/Ins', '% Exp/Vot', 'Nuance Liste',
       'Libellé Abrégé Liste', 'Voix', '% Voix/Ins', '% Voix/Exp',
       'rang_liste'],
      dtype='object')
df 2008  Index(['Date export', 'Code du département', 'Libellé du département',
       'Code de la commune', 'Libellé de la commune', 'Code du bureau de vote',
       'Inscrits', 'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins',
       'Blancs et nuls', '% BlNuls/Ins', '% BlNuls/Vot', 'Exprimés',
       '% Exp/Ins', '% Exp/Vot', 'Code Nuance', 'Sexe', 'Nom', 'Prénom',
       'Liste', 'Sièges', 'Voix', '% Voix/Ins', '% Voix/Exp'],
      dtype='object')
df 2014  Index(['N° tour', 'Code département', 'Code commune', 'Nom de la commune',
       'N° de bureau de vote ', 'Inscrits', ' Votants', ' Exprimés',
       'N° de dépôt de la liste', 'Nom du candidat tête de liste',
       'Prénom du candidat  tête de liste', 'Code nuance de la liste ',
       'Nombre de voix '],
      dtype='object')
df 2020 tour 1 Index(['Code du département', 'Libellé du département', 'Code de la commune',
       'Libellé de la commune', 'Code du bureau de vote', 'Inscrits',
       'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins', 'Blancs',
       '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins', '% Nuls/Vot',
       'Exprimés', '% Exp/Ins', '% Exp/Vot', 'N.Pan.', 'Code Nuance', 'Sexe',
       'Nom', 'Prénom', 'Liste', 'Voix', '% Voix/Ins', '% Voix/Exp'],
      dtype='object')
df 2020 tour 2 Index(['Code du département', 'Libellé du département', 'Code de la commune',
       'Libellé de la commune', 'Code du bureau de vote', 'Inscrits',
       'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins', 'Blancs',
       '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins', '% Nuls/Vot',
       'Exprimés', '% Exp/Ins', '% Exp/Vot', 'N.Pan.', 'Code Nuance', 'Sexe',
       'Nom', 'Prénom', 'Liste', 'Voix', '% Voix/Ins', '% Voix/Exp'],
      dtype='object')

colonne a garder
geo
exprimé (population)
votant
abstention (expr - votant)
% peuvent être recalculé pas important
nuance

A prendre en compte
la notion de tour en 2001 2008 le site dit qu'il y a le tour 1 et 2 mais jsp comment les distinguer s'il y a une somme des deux tours ou si y a que le dernier tour
en 2020 la nuance la plus utilisé est NC donc faut essayer de comprendre si c'est normal ou s'il faut rajouter des données
faire attention car pas toutes les années sont distinguées par bureau de vote lorsqu'il y a le bureau de vote il y a la personne voir s'il faut perdre la données ou si on peut la rajouter