In [1]:
import os
import sys

In [2]:
sys.path.append(os.path.abspath('../..'))

In [3]:
from src.preprocessing import load_and_clean_ville_stats

In [4]:
df = load_and_clean_ville_stats()
df.head()

,id_election,id_brut_miom,code_departement,libelle_departement,code_canton,libelle_canton,code_commune,libelle_commune,code_circonscription,libelle_circonscription,...,nuls,exprimes,ratio_abstentions_inscrits,ratio_votants_inscrits,ratio_blancs_inscrits,ratio_blancs_votants,ratio_nuls_inscrits,ratio_nuls_votants,ratio_exprimes_inscrits,ratio_exprimes_votants
0,2026_muni_t2,01160_0001,01,Ain,NaN,NaN,01160,Ferney-Voltaire,NaN,NaN,...,9,380,57.50,42.50,0.54,1.27,0.97,2.28,40.99,96.45
1,2026_muni_t2,01160_0002,01,Ain,NaN,NaN,01160,Ferney-Voltaire,NaN,NaN,...,9,475,59.29,40.71,0.58,1.43,0.75,1.83,39.39,96.74
2,2026_muni_t2,01160_0003,01,Ain,NaN,NaN,01160,Ferney-Voltaire,NaN,NaN,...,4,421,62.67,37.33,1.44,3.85,0.34,0.90,35.56,95.25
3,2026_muni_t2,01160_0004,01,Ain,NaN,NaN,01160,Ferney-Voltaire,NaN,NaN,...,5,621,46.02,53.98,0.43,0.79,0.43,0.79,53.12,98.42
4,2026_muni_t2,01194_0001,01,Ain,NaN,NaN,01194,Jassans-Riottier,NaN,NaN,...,1,653,37.21,62.79,1.50,2.39,0.09,0.15,61.20,97.46

In [5]:
df.shape

(3162440, 25)

In [6]:
df['id_election'].value_counts()

id_election
2024_euro_t1    70104
2024_legi_t1    70102
2026_muni_t1    70003
2022_pres_t2    69682
2022_pres_t1    69682
2022_legi_t1    69682
2022_legi_t2    69355
2019_euro_t1    69297
2017_legi_t1    69242
2017_pres_t2    69242
2017_pres_t1    69242
2020_muni_t1    68941
2017_legi_t2    68767
2021_regi_t1    68611
2021_regi_t2    68611
2014_euro_t1    68246
2014_muni_t1    68169
2012_legi_t1    67932
2012_pres_t1    67932
2012_pres_t2    67932
2015_regi_t1    67776
2015_regi_t2    67776
2009_euro_t1    66583
2010_regi_t1    66222
2021_dpmt_t1    66016
2010_regi_t2    65842
2015_dpmt_t1    65781
2007_legi_t1    65618
2007_pres_t1    65617
2007_pres_t2    65617
2004_euro_t1    64761
2002_pres_t2    64141
2002_pres_t1    64141
1999_euro_t1    63737
2002_legi_t1    63394
2012_legi_t2    62633
2004_regi_t1    62573
2021_dpmt_t2    62063
2004_regi_t2    61966
2024_legi_t2    61615
2015_dpmt_t2    60975
2002_legi_t2    57575
2007_legi_t2    51779
2011_cant_t1    32934
2008_cant_t1    32646
2004_cant_t1    32106
2001_cant_t1    31772
2011_cant_t2    27023
2008_muni_t1    25926
2004_cant_t2    24817
2014_muni_t2    22480
2001_cant_t2    21218
2020_muni_t2    19594
2008_cant_t2    17689
2026_muni_t2    17398
2008_muni_t2    11862
Name: count, dtype: int64

In [8]:
df = df[df['id_election'].isin(['2020_muni_t1', '2014_muni_t1', '2008_muni_t1'])]

In [9]:
df

,id_election,id_brut_miom,code_departement,libelle_departement,code_canton,libelle_canton,code_commune,libelle_commune,code_circonscription,libelle_circonscription,...,nuls,exprimes,ratio_abstentions_inscrits,ratio_votants_inscrits,ratio_blancs_inscrits,ratio_blancs_votants,ratio_nuls_inscrits,ratio_nuls_votants,ratio_exprimes_inscrits,ratio_exprimes_votants
859265,2008_muni_t1,97101_0001,ZA,Guadeloupe,NaN,NaN,97101,Les Abymes,NaN,NaN,...,14,348,32.96,67.04,NaN,NaN,2.59,3.87,64.44,96.13
859266,2008_muni_t1,97101_0002,ZA,Guadeloupe,NaN,NaN,97101,Les Abymes,NaN,NaN,...,19,156,35.90,64.10,NaN,NaN,6.96,10.86,57.14,89.14
859267,2008_muni_t1,97101_0003,ZA,Guadeloupe,NaN,NaN,97101,Les Abymes,NaN,NaN,...,18,440,35.40,64.60,NaN,NaN,2.54,3.93,62.06,96.07
859268,2008_muni_t1,97101_0004,ZA,Guadeloupe,NaN,NaN,97101,Les Abymes,NaN,NaN,...,17,422,34.96,65.04,NaN,NaN,2.52,3.87,62.52,96.13
859269,2008_muni_t1,97101_0005,ZA,Guadeloupe,NaN,NaN,97101,Les Abymes,NaN,NaN,...,32,554,34.67,65.33,NaN,NaN,3.57,5.46,61.76,94.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139955,2014_muni_t1,98758_0003,ZP,Polynésie française,NaN,NaN,98758,Uturoa,NaN,NaN,...,12,837,24.20,75.80,NaN,NaN,1.07,1.41,74.73,98.59
3139956,2014_muni_t1,97501_0001,ZS,Saint-Pierre-et-Miquelon,NaN,NaN,97501,Miquelon-Langlade,NaN,NaN,...,1,410,17.14,82.86,NaN,NaN,0.20,0.24,82.66,99.76
3139957,2014_muni_t1,97502_0001,ZS,Saint-Pierre-et-Miquelon,NaN,NaN,97502,Saint-Pierre,NaN,NaN,...,61,932,30.66,69.34,NaN,NaN,4.26,6.14,65.08,93.86
3139958,2014_muni_t1,97502_0002,ZS,Saint-Pierre-et-Miquelon,NaN,NaN,97502,Saint-Pierre,NaN,NaN,...,87,938,30.60,69.40,NaN,NaN,5.89,8.49,63.51,91.51
3139959,2014_muni_t1,97502_0003,ZS,Saint-Pierre-et-Miquelon,NaN,NaN,97502,Saint-Pierre,NaN,NaN,...,91,956,31.84,68.16,NaN,NaN,5.92,8.69,62.24,91.31